name: tests
on:
  push:
    branches:
      - 'main'
    paths:
      - 'Sources/**'
      - 'Tests/**'
  pull_request:
    branches:
      - 'main'
jobs:
  code-edit-kit-tests:
    name: Testing CodeEditKit
    runs-on: [self-hosted, macOS]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Testing Package
        run: exec ./.github/scripts/tests.sh arm
